# server.port=8761

# http://localhost:8761/
server:
  port: 8761


eureka:
  client:
    # this is a eureka server, we don't have to fetch registry from any other place.
    fetch-registry: false
    register-with-eureka: false
  # eureka.server.enable-self-preservation=false If a significant portion of the registered instances stops delivering heartbeats within a time span,
  # Eureka assumes the issue is due to the network and does not de-register the services that are not responding.
  # This is Eureka self-preservation mode.
  # Leaving this set to true is probably a good idea,
  # but it also means that if you have a small set of instances th a few nodes then you won't see the expected
  # behavior when instances de-register.
  # server:
  #  enable-self-preservation: false

  # https://cloud.spring.io/spring-cloud-netflix/reference/html/#netflix-eureka-client-starter


  freemarker:
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false
