server:
  port: 8888

spring:
  application:
    name: configserver

  cloud:
    config:
      server:
        git:
          uri: https://github.com/jlmc/micro-config-repo # http uri coped from the browser address
          search-paths: warehouse-service, bookingms  # GitHub repo root folders
          default-label: master # branch name, it could be useful to have multiple environments, DEV, QA, PROD...
          username: costajlmpp@gmail.com
          # password: <you dev token>
          refresh-rate: 1

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
