server:
  port: 8888

spring:
  application:
    name: configserver

  profiles:
    active: native

  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/Documents/junks/projects/spring/cloud/spring-cloud-cargo-tracker/cloud/config-repo
        git:
          refresh-rate: 1

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
