server:
  port: 8082

spring:
  application:
    name: routingms
  profiles:
    active: default, dev

  zipkin:
    base-url: "http://localhost:9411/"

## Service Discovery
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
    healthcheck:
      enabled: true

  instance:
    # what distinct ID do we want for each registered service, we can override the default attribution
    # instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    # instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}}
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}:${random.value}
    lease-renewal-interval-in-seconds: 30


## Actuator
### $ curl localhost:8082/actuator/health -d {} -H "Content-Type: application/json"
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: '*'


logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: DEBUG
