spring:
  application:
    name: tracking-ms

  rabbitmq:
    host: locahost
    port: 5672
    password: guest
    username: guest

#  spring.cloud.stream.bindings.input.destination=cargoRoutings
#  spring.cloud.stream.bindings.input.group=cargoRoutingsQueue
  cloud:
    stream:
      bindings:
        routings:
          destination: cargoRoutings
          group: cargoRoutingsQueue
#        bookings:
#          destination: cargoBookings
#          group: cargoBookingsQueue
